{
  "Material": 204419,
  "Material Description": "COSMOS. BRC-M-EI*BA5*NO",
  "DF stor. loc. level": "",
  "Unrestricted": 0,
  "Base Unit of Measure": "KG",
  "Currency": "USD",
  "Value Unrestricted": 0,
  "Storage Location": "P001",
  "Batch": "0000714783",
  "Vendor Batch": "2020090007",
  "SLED/BBD": 44818,
  "Last goods receipt": 44096,
  "Plant": "USKL",
  "Blocked": 10,
  "Value BlockedStck": 1676.98,
  "Manufacturer/Vendor": "10200075",
  "Name 1": "Adm Kinetik Distribution LLC",
  "GIN code": "103036",
  "GIN-Code Index": "00",
  "Material Type": "OMYA",
  "Material Group": "80001000",
  "Created On": 44418,
  "Stock in transfer": 0,
  "Value in StkTransf": 0,
  "In Quality Insp.": 0,
  "Value in QualInsp.": 0,
  "Restricted-Use Stock": 0,
  "Value Restrictd": 0,
  "Returns": 0,
  "Valeu ReturnsBlock": 0,
  "Safety Stock": 0,
  "Country of origin": "CH",
  "Region of origin": "SO",
  "Location": ""
}